version: '3.9'

services:
  datafeed-socket-1:
    build: .
    ports: 
      - 3001:3000
    environment:
      - TZ=Asia/Ho_Chi_Minh
  datafeed-socket-2:
    build: .
    ports: 
      - 3002:3000
    environment:
      - TZ=Asia/Ho_Chi_Minh      
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"